"""create info table

Revision ID: 23b5816b8dcb
Revises: d2d0eb2fe55a
Create Date: 2017-09-02 22:41:02.248288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '23b5816b8dcb'
down_revision = 'd2d0eb2fe55a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('infos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('contact_name', sa.String(length=30), nullable=True),
    sa.Column('telphone', sa.String(length=11), nullable=False),
    sa.Column('wx', sa.String(length=50), nullable=True),
    sa.Column('audit_user', sa.Integer(), nullable=True),
    sa.Column('audited', sa.Boolean(), nullable=True),
    sa.Column('show', sa.Boolean(), nullable=True),
    sa.Column('info_type_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['audit_user'], ['users.id'], ),
    sa.ForeignKeyConstraint(['info_type_id'], ['info_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infos_telphone'), 'infos', ['telphone'], unique=False)
    op.alter_column(u'users', 'confirmed',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column(u'users', 'freezed',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'users', 'freezed',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column(u'users', 'confirmed',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_index(op.f('ix_infos_telphone'), table_name='infos')
    op.drop_table('infos')
    # ### end Alembic commands ###
